### ISSUE TITLE
Installing rendering dependencies doesn't fix "go_vncdriver was installed without OpenGL support" error.

### ISSUE THREAD

**Issue by TomSil** [openai/go-vncdriver#17]
I was trying to run  a file called demo.py:
```
import gym
import universe  # register the universe environments

env = gym.make('flashgames.DuskDrive-v0')
env.configure(remotes=1)  # automatically creates a local docker container
observation_n = env.reset()

while True:
  action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n]  # your agent here
  observation_n, reward_n, done_n, info = env.step(action_n)
  env.render()

```
But I got the error message:
go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.

I then ran the code under the installation heading of this repository and reinstalled go-vncdriver, but the bug persists.

Anyone know why this might be?

Some things that might help:
- When I try and search for libx... files on my Ubuntu hard drive I can't find them.
-This is the error report:

```
universe-OXQ5bY-0 | [2017-01-01 00:43:01,575] [INFO:universe.rewarder.remote] WebSocket connection established
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    env.render()
  File "/home/tomsil/miniconda3/envs/universe/lib/python3.6/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/tomsil/miniconda3/envs/universe/lib/python3.6/site-packages/gym/core.py", line 344, in _render
    return self.env.render(mode, close)
  File "/home/tomsil/miniconda3/envs/universe/lib/python3.6/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/tomsil/universe/universe/wrappers/render.py", line 49, in _render
    return self.env.render(mode=mode, *args, **kwargs)
  File "/home/tomsil/miniconda3/envs/universe/lib/python3.6/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/tomsil/miniconda3/envs/universe/lib/python3.6/site-packages/gym/core.py", line 344, in _render
    return self.env.render(mode, close)
  File "/home/tomsil/miniconda3/envs/universe/lib/python3.6/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/tomsil/universe/universe/envs/vnc_env.py", line 537, in _render
    self.vnc_session.render(self.connection_names[0])
go_vncdriver.Error: /home/tomsil/universe/go-vncdriver/.build/src/github.com/openai/go-vncdriver/main.go:387: go_vncdriver was installed without OpenGL support. See https://github.com/openai/go-vncdriver for details on how debug.
[2017-01-01 00:43:01,765] Killing and removing container: id=7af960f9ff7adf7cf1f06426f0f352488e9572a6c9699f535e9579bf76c22e5b. (If this command errors, you can always kill all automanaged environments on this Docker daemon via: docker rm -f $(docker ps -q -a -f 'label=com.openai.automanaged=true')
```

- When I try to run the demo.py file line by line in the linux terminal, the line `env.configure(remotes=1)`
causes the terminal to endlessly spew out various commands preceded by `universe-OXQ5bY-0 |`

Thanks for any help
- Tom

**Comment by beolson** [comment]
I ran into a similar error and managed to get it working by deleting the following folders

-  ~/.local/lib/python2.7/site-packages/go_vncdriver
- ~/.local/lib/python2.7/site-packages/go_vncdriver-0.4.19.dist-info

Not very familiar with Python, but I think what is happening is when you install the gym dependency, it is pulling in a different version of the go_vncdriver package than the one you built with OpenGL support.  

Anyways, deleting those 2 folders got it working for me.

**Comment by TomSil** [comment]
Thanks for the response beolson, I will try it when I get time.

**Comment by panwarab** [comment]
@TomSil @beolson did you find any fix for the problem?

**Comment by jamesrichter** [comment]
I uninstalled, then reinstalled the VNC driver using the instructions here: https://github.com/openai/go-vncdriver
It worked for me.

**Comment by jamesrichter** [comment]
I uninstalled, then reinstalled the VNC driver using these directions: https://github.com/openai/go-vncdriver
Note that you have to reinstall the driver after you get the new dependencies, not before.  Simply adding the dependencies afterwards does not work.

**Comment by Vmphuc** [comment]
Thank **beolson** , It work with me, I use Python3.
After setup go-vncdriver, and go /python3.5/site-packages and do as you talk.

**Comment by kepma** [comment]
I can't  resolve this problem after delete these two floders.
There exists error:ModuleNotFoundError: No module named 'go_vncdriver'
