### ISSUE TITLE
Error building on Manjaro

### ISSUE THREAD

**Issue by arvid123** [openai/go-vncdriver#38]
Hey, i'm trying to install go-vncdriver for universe and when i run `sudo python setup.py build` i get this output:
```
`running build
Running new build
Env info:

export GOPATH='/home/arvid/go-vncdriver/.build'
export GO15VENDOREXPERIMENT='1'
export CGO_CFLAGS='-I/usr/lib/python3.7/site-packages/numpy/core/include -I/usr/include/python3.7m'
export CGO_LDFLAGS='ld -L/usr/lib -lpython3.7m'

Running build with OpenGL rendering.
Building with OpenGL: GOPATH=/home/arvid/go-vncdriver/.build go build -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver. (Set GO_VNCDRIVER_NOGL to build without OpenGL.)
# runtime/cgo
gcc: error: ld: No such file or directory

Note: could not build with OpenGL rendering (cf https://github.com/openai/go-vncdriver). This is expected on most servers. Going to try building without OpenGL.
Building without OpenGL: GOPATH=/home/arvid/go-vncdriver/.build go build -tags no_gl -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver
# runtime/cgo
gcc: error: ld: No such file or directory
Could not build go_vncdriver: 
Build failed. HINT:

- Ensure you have your Python development headers installed. (On Ubuntu,
  this is just 'sudo apt-get install python-dev'.

Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    install_requires=['numpy'],
  File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 23, in run
    self.build()
  File "setup.py", line 61, in build
    build.build()
  File "/home/arvid/go-vncdriver/build.py", line 114, in build
    build_no_gl()
  File "/home/arvid/go-vncdriver/build.py", line 95, in build_no_gl
    ''')
build.BuildException: 
Build failed. HINT:

- Ensure you have your Python development headers installed. (On Ubuntu,
  this is just 'sudo apt-get install python-dev'.
`
```
Im running Manjaro linux v 18.1.2

**Comment by worry80** [comment]
I got the same output, I can't find any answer to solve this problem

**Comment by worry80** [comment]
I have just fixed this problem by modifying the build.py file, Change build.py 45 lines `"/usr/lib/x86_64-linux-gnu/libjpeg.so"` to `"/usr/lib/libjpeg.so."` No error message indicates that the compilation was successful, and then the installation is done using `"pip Install -e . "`.
