### ISSUE TITLE
Building wheel for go-vncdriver (setup.py) ... error +. Setup: MacOS Mojave + Python 3.5

### ISSUE THREAD

**Issue by puxama** [openai/go-vncdriver#40]
I have this message when I try to install Universe or vncdriver.
¿Someone can help me plz?

Building wheel for go-vncdriver (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/dennis/virtualenvs/relearning/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-wheel-tga4kfq9
       cwd: /private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/
  Complete output (55 lines):
  running bdist_wheel
  running build
  Running new build
  Env info:
  
  export GO15VENDOREXPERIMENT='1'
  export CGO_CFLAGS='-I/Users/dennis/virtualenvs/relearning/lib/python3.5/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m'
  export CGO_LDFLAGS='/usr/local/opt/jpeg-turbo/lib/libjpeg.dylib -undefined dynamic_lookup'
  export GOPATH='/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/.build'
  
  Running build with OpenGL rendering.
  Building with OpenGL: GOPATH=/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/.build go build -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver. (Set GO_VNCDRIVER_NOGL to build without OpenGL.)
  no required module provides package github.com/openai/go-vncdriver: working directory is not part of a module
  
  Note: could not build with OpenGL rendering (cf https://github.com/openai/go-vncdriver). This is expected on most servers. Going to try building without OpenGL.
  Building without OpenGL: GOPATH=/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/.build go build -tags no_gl -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver
  no required module provides package github.com/openai/go-vncdriver: working directory is not part of a module
  Could not build go_vncdriver:
  Build failed. HINT:
  
  - Ensure you have your Python development headers installed. (On Ubuntu,
    this is just 'sudo apt-get install python-dev'.
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py", line 75, in <module>
      install_requires=['numpy'],
    File "/Users/dennis/virtualenvs/relearning/lib/python3.5/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/dennis/virtualenvs/relearning/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py", line 23, in run
      self.build()
    File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py", line 61, in build
      build.build()
    File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/build.py", line 114, in build
      build_no_gl()
    File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/build.py", line 95, in build_no_gl
      ''')
  build.BuildException:
  Build failed. HINT:
  
  - Ensure you have your Python development headers installed. (On Ubuntu,
    this is just 'sudo apt-get install python-dev'.
  
  ----------------------------------------
  ERROR: Failed building wheel for go-vncdriver
  Running setup.py clean for go-vncdriver
  Building wheel for gym (setup.py) ... done
  Created wheel for gym: filename=gym-0.7.4-py3-none-any.whl size=204692 sha256=cae48942ac7de8ed26c1fae04761ee51e0c08534dfb302d310340232ea13f79a
  Stored in directory: /Users/dennis/Library/Caches/pip/wheels/c5/26/38/1e640c85a7db5871613e0d569c4297fff415d595a144671944
Successfully built gym
Failed to build go-vncdriver
Installing collected packages: gym, go-vncdriver, fastzbarlight, docker-py, autobahn, universe
  Attempting uninstall: gym
    Found existing installation: gym 0.17.3
    Uninstalling gym-0.17.3:
      Successfully uninstalled gym-0.17.3
    Running setup.py install for go-vncdriver ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/dennis/virtualenvs/relearning/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-record-eu0nyupl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dennis/virtualenvs/relearning/include/site/python3.5/go-vncdriver
         cwd: /private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/
    Complete output (57 lines):
    running install
    running build
    Running new build
    Env info:
    
    export GOPATH='/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/.build'
    export CGO_LDFLAGS='/usr/local/opt/jpeg-turbo/lib/libjpeg.dylib -undefined dynamic_lookup'
    export CGO_CFLAGS='-I/Users/dennis/virtualenvs/relearning/lib/python3.5/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m'
    export GO15VENDOREXPERIMENT='1'
    
    Running build with OpenGL rendering.
    Building with OpenGL: GOPATH=/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/.build go build -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver. (Set GO_VNCDRIVER_NOGL to build without OpenGL.)
    no required module provides package github.com/openai/go-vncdriver: working directory is not part of a module
    
    Note: could not build with OpenGL rendering (cf https://github.com/openai/go-vncdriver). This is expected on most servers. Going to try building without OpenGL.
    Building without OpenGL: GOPATH=/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/.build go build -tags no_gl -buildmode=c-shared -o go_vncdriver.so github.com/openai/go-vncdriver
    no required module provides package github.com/openai/go-vncdriver: working directory is not part of a module
    Could not build go_vncdriver:
    Build failed. HINT:
    
    - Ensure you have your Python development headers installed. (On Ubuntu,
      this is just 'sudo apt-get install python-dev'.
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py", line 75, in <module>
        install_requires=['numpy'],
      File "/Users/dennis/virtualenvs/relearning/lib/python3.5/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/dennis/virtualenvs/relearning/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py", line 23, in run
        self.build()
      File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py", line 61, in build
        build.build()
      File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/build.py", line 114, in build
        build_no_gl()
      File "/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/build.py", line 95, in build_no_gl
        ''')
    build.BuildException:
    Build failed. HINT:
    
    - Ensure you have your Python development headers installed. (On Ubuntu,
      this is just 'sudo apt-get install python-dev'.
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dennis/virtualenvs/relearning/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-install-dks8lxlo/go-vncdriver_2d414f74052047c998a5e5a51a457ed5/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/cw/264vdnpj2qv5jvm2clnnx7dm0000gn/T/pip-record-eu0nyupl/install-record.txt --single-version-externally-managed --compile --install-headers /Users/dennis/virtualenvs/relearning/include/site/python3.5/go-vncdriver Check the logs for full command output.

**Comment by qjy-liveforover** [comment]
Have you solved it yet?
